// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Model;

namespace PPA1.Migrations
{
    [DbContext(typeof(LogContext))]
    partial class LogContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Model.BMILog", b =>
                {
                    b.Property<DateTime>("timestamp")
                        .HasColumnType("datetime2");

                    b.Property<double>("heightFeet")
                        .HasColumnType("float");

                    b.Property<double>("heightInches")
                        .HasColumnType("float");

                    b.Property<string>("result")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("weight")
                        .HasColumnType("float");

                    b.HasKey("timestamp");

                    b.ToTable("BMILogs");
                });

            modelBuilder.Entity("Model.DistanceLog", b =>
                {
                    b.Property<DateTime>("timestamp")
                        .HasColumnType("datetime2");

                    b.Property<double>("result")
                        .HasColumnType("float");

                    b.Property<double>("x1")
                        .HasColumnType("float");

                    b.Property<double>("x2")
                        .HasColumnType("float");

                    b.Property<double>("y1")
                        .HasColumnType("float");

                    b.Property<double>("y2")
                        .HasColumnType("float");

                    b.HasKey("timestamp");

                    b.ToTable("DistanceLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
